spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

    listener:
      simple:
        concurrency: 4
        max-concurrency: 4
        prefetch: 1
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3